import type { Worker, Emergency, Company, SafetyOfficer, MonthlyData, ChartDataPoint } from '@/types';

export const COMPANIES: Company[] = [
  { id: 'sonatrach', name: 'Sonatrach', code: 'SNTR', industry: 'Pétrole & Gaz', address: 'Val d\'Hydra, Alger', maxWorkers: 300, currentWorkers: 247 },
  { id: 'cevital', name: 'CEVITAL', code: 'CVTL', industry: 'Agroalimentaire', address: 'Béjaïa, Algérie', maxWorkers: 150, currentWorkers: 132 },
  { id: 'arcelormittal', name: 'ArcelorMittal', code: 'ARCL', industry: 'Sidérurgie', address: 'Annaba, Algérie', maxWorkers: 200, currentWorkers: 178 },
];

export const WORKERS: Worker[] = [
  { id:'w1', employeeId:'SN-001', firstName:'Ahmed', lastName:'Mansouri', unit:'Unité A - Raffinage', department:'Production', position:'Technicien', phone:'0551234567', status:'active', bloodType:'O+', lastSeen: new Date(Date.now()-5*60000).toISOString(), joinDate:'2019-03-15', companyId:'sonatrach', medicalProfile:{ bloodType:'O+', allergies:['Pénicilline','Aspirine'], chronicDiseases:['Hypertension'], medications:['Amlodipine 5mg'], emergencyNotes:'Patient hypertendu. Éviter stress intense. Contacter cardiologue en cas d\'urgence cardiaque.', iceContact:{name:'Fatima Mansouri', relation:'Épouse', phone:'0661234567'}, lastCheckup:'2024-11-20' } },
  { id:'w2', employeeId:'SN-002', firstName:'Youcef', lastName:'Benmoussa', unit:'Unité B - Stockage', department:'Logistique', position:'Chef d\'équipe', phone:'0552345678', status:'active', bloodType:'A+', lastSeen: new Date(Date.now()-2*60000).toISOString(), joinDate:'2017-06-01', companyId:'sonatrach', medicalProfile:{ bloodType:'A+', allergies:['Sulfamides'], chronicDiseases:['Diabète type 2'], medications:['Metformine 500mg'], emergencyNotes:'Diabétique. Vérifier glycémie en cas de malaise.', iceContact:{name:'Karim Benmoussa', relation:'Frère', phone:'0662345678'}, lastCheckup:'2025-01-10' } },
  { id:'w3', employeeId:'SN-003', firstName:'Rachid', lastName:'Ferhat', unit:'Unité C - Forage', department:'Extraction', position:'Ingénieur forage', phone:'0553456789', status:'offline', bloodType:'B+', lastSeen: new Date(Date.now()-45*60000).toISOString(), joinDate:'2020-09-10', companyId:'sonatrach', medicalProfile:{ bloodType:'B+', allergies:[], chronicDiseases:[], medications:[], emergencyNotes:'Aucune condition particulière.', iceContact:{name:'Nadia Ferhat', relation:'Sœur', phone:'0663456789'}, lastCheckup:'2024-08-05' } },
  { id:'w4', employeeId:'SN-004', firstName:'Khaled', lastName:'Aoudia', unit:'Unité A - Raffinage', department:'Sécurité', position:'Agent HSE', phone:'0554567890', status:'active', bloodType:'AB+', lastSeen: new Date(Date.now()-1*60000).toISOString(), joinDate:'2021-01-20', companyId:'sonatrach', medicalProfile:{ bloodType:'AB+', allergies:['Latex'], chronicDiseases:['Asthme'], medications:['Ventoline'], emergencyNotes:'Asthmatique. Tenir un inhalateur disponible.', iceContact:{name:'Samira Aoudia', relation:'Épouse', phone:'0664567890'}, lastCheckup:'2025-02-14' } },
  { id:'w5', employeeId:'SN-005', firstName:'Mourad', lastName:'Belkacemi', unit:'Unité D - Maintenance', department:'Technique', position:'Mécanicien', phone:'0555678901', status:'active', bloodType:'O-', lastSeen: new Date(Date.now()-8*60000).toISOString(), joinDate:'2018-11-05', companyId:'sonatrach', medicalProfile:{ bloodType:'O-', allergies:['Iode'], chronicDiseases:['Épilepsie'], medications:['Dépakine 500mg'], emergencyNotes:'Épileptique. Ne pas immobiliser en crise. Appeler SAMU immédiatement.', iceContact:{name:'Brahim Belkacemi', relation:'Père', phone:'0665678901'}, lastCheckup:'2024-12-01' } },
  { id:'w6', employeeId:'SN-006', firstName:'Sofiane', lastName:'Hadjadj', unit:'Unité B - Stockage', department:'Production', position:'Opérateur', phone:'0556789012', status:'active', bloodType:'A-', lastSeen: new Date(Date.now()-3*60000).toISOString(), joinDate:'2022-04-18', companyId:'sonatrach', medicalProfile:{ bloodType:'A-', allergies:[], chronicDiseases:['Hypertension'], medications:['Lisinopril 10mg'], emergencyNotes:'', iceContact:{name:'Leila Hadjadj', relation:'Épouse', phone:'0666789012'}, lastCheckup:'2025-01-28' } },
  { id:'w7', employeeId:'SN-007', firstName:'Amar', lastName:'Zidane', unit:'Unité C - Forage', department:'Extraction', position:'Foreur', phone:'0557890123', status:'emergency', bloodType:'B-', lastSeen: new Date().toISOString(), joinDate:'2016-07-22', companyId:'sonatrach', medicalProfile:{ bloodType:'B-', allergies:['Pénicilline','AINS'], chronicDiseases:['Cardiopathie ischémique'], medications:['Aspirine 100mg','Atorvastatine'], emergencyNotes:'Antécédents cardiaques. Défibrillateur disponible à l\'unité C.', iceContact:{name:'Zineb Zidane', relation:'Épouse', phone:'0667890123'}, lastCheckup:'2024-10-15' } },
  { id:'w8', employeeId:'SN-008', firstName:'Kamel', lastName:'Bouzid', unit:'Unité D - Maintenance', department:'Électricité', position:'Électricien', phone:'0558901234', status:'active', bloodType:'O+', lastSeen: new Date(Date.now()-12*60000).toISOString(), joinDate:'2019-08-30', companyId:'sonatrach', medicalProfile:{ bloodType:'O+', allergies:[], chronicDiseases:[], medications:[], emergencyNotes:'', iceContact:{name:'Djamila Bouzid', relation:'Mère', phone:'0668901234'}, lastCheckup:'2024-09-20' } },
  { id:'w9', employeeId:'CV-001', firstName:'Lamine', lastName:'Cherif', unit:'Ligne Production 1', department:'Fabrication', position:'Conducteur machine', phone:'0559012345', status:'active', bloodType:'A+', lastSeen: new Date(Date.now()-6*60000).toISOString(), joinDate:'2020-02-14', companyId:'cevital', medicalProfile:{ bloodType:'A+', allergies:['Noix'], chronicDiseases:[], medications:[], emergencyNotes:'Allergie sévère aux noix. EpiPen disponible.', iceContact:{name:'Meriem Cherif', relation:'Épouse', phone:'0669012345'}, lastCheckup:'2025-01-05' } },
  { id:'w10', employeeId:'CV-002', firstName:'Nassim', lastName:'Ouali', unit:'Ligne Production 2', department:'Qualité', position:'Contrôleur qualité', phone:'0550123456', status:'offline', bloodType:'AB-', lastSeen: new Date(Date.now()-90*60000).toISOString(), joinDate:'2021-07-19', companyId:'cevital', medicalProfile:{ bloodType:'AB-', allergies:[], chronicDiseases:['Arthrite'], medications:['Ibuprofène'], emergencyNotes:'', iceContact:{name:'Salim Ouali', relation:'Frère', phone:'0660123456'}, lastCheckup:'2024-11-10' } },
  { id:'w11', employeeId:'CV-003', firstName:'Hamza', lastName:'Kerboua', unit:'Entrepôt', department:'Logistique', position:'Magasinier', phone:'0551112222', status:'active', bloodType:'O+', lastSeen: new Date(Date.now()-4*60000).toISOString(), joinDate:'2023-01-09', companyId:'cevital', medicalProfile:{ bloodType:'O+', allergies:[], chronicDiseases:[], medications:[], emergencyNotes:'', iceContact:{name:'Yasmine Kerboua', relation:'Sœur', phone:'0661112222'}, lastCheckup:'2024-12-20' } },
  { id:'w12', employeeId:'AR-001', firstName:'Bilal', lastName:'Meziane', unit:'Haut-fourneau 1', department:'Fusion', position:'Opérateur four', phone:'0552223333', status:'active', bloodType:'B+', lastSeen: new Date(Date.now()-7*60000).toISOString(), joinDate:'2018-04-25', companyId:'arcelormittal', medicalProfile:{ bloodType:'B+', allergies:['Nickel'], chronicDiseases:['Bronchite chronique'], medications:['Bromhexine'], emergencyNotes:'Exposition régulière aux fumées. Surveiller fonction respiratoire.', iceContact:{name:'Houria Meziane', relation:'Épouse', phone:'0662223333'}, lastCheckup:'2025-02-01' } },
  { id:'w13', employeeId:'AR-002', firstName:'Walid', lastName:'Boumaza', unit:'Laminoir', department:'Transformation', position:'Lamineur', phone:'0553334444', status:'active', bloodType:'A+', lastSeen: new Date(Date.now()-15*60000).toISOString(), joinDate:'2017-10-11', companyId:'arcelormittal', medicalProfile:{ bloodType:'A+', allergies:[], chronicDiseases:['Hypertension'], medications:['Amlodipine'], emergencyNotes:'', iceContact:{name:'Sabrina Boumaza', relation:'Épouse', phone:'0663334444'}, lastCheckup:'2024-10-30' } },
  { id:'w14', employeeId:'AR-003', firstName:'Tarek', lastName:'Ghilas', unit:'Haut-fourneau 2', department:'Fusion', position:'Chef d\'équipe', phone:'0554445555', status:'offline', bloodType:'O+', lastSeen: new Date(Date.now()-120*60000).toISOString(), joinDate:'2015-06-30', companyId:'arcelormittal', medicalProfile:{ bloodType:'O+', allergies:[], chronicDiseases:[], medications:[], emergencyNotes:'', iceContact:{name:'Nour Ghilas', relation:'Épouse', phone:'0664445555'}, lastCheckup:'2025-01-15' } },
  { id:'w15', employeeId:'SN-009', firstName:'Fares', lastName:'Bendjama', unit:'Unité A - Raffinage', department:'Chimie', position:'Chimiste', phone:'0555556666', status:'active', bloodType:'A-', lastSeen: new Date(Date.now()-9*60000).toISOString(), joinDate:'2022-08-01', companyId:'sonatrach', medicalProfile:{ bloodType:'A-', allergies:['Produits chimiques acides'], chronicDiseases:[], medications:[], emergencyNotes:'Sensibilité cutanée aux acides. EPI obligatoire.', iceContact:{name:'Rania Bendjama', relation:'Épouse', phone:'0665556666'}, lastCheckup:'2024-07-12' } },
  { id:'w16', employeeId:'SN-010', firstName:'Reda', lastName:'Tlemcani', unit:'Unité B - Stockage', department:'Sécurité', position:'Pompier industriel', phone:'0556667777', status:'active', bloodType:'B+', lastSeen: new Date(Date.now()-2*60000).toISOString(), joinDate:'2020-12-01', companyId:'sonatrach', medicalProfile:{ bloodType:'B+', allergies:[], chronicDiseases:[], medications:[], emergencyNotes:'', iceContact:{name:'Amina Tlemcani', relation:'Mère', phone:'0666667777'}, lastCheckup:'2025-02-20' } },
  { id:'w17', employeeId:'CV-004', firstName:'Samir', lastName:'Bensaid', unit:'Ligne Production 3', department:'Fabrication', position:'Technicien maintenance', phone:'0557778888', status:'active', bloodType:'AB+', lastSeen: new Date(Date.now()-18*60000).toISOString(), joinDate:'2021-05-17', companyId:'cevital', medicalProfile:{ bloodType:'AB+', allergies:[], chronicDiseases:['Psoriasis'], medications:['Cortisone crème'], emergencyNotes:'', iceContact:{name:'Dalila Bensaid', relation:'Épouse', phone:'0667778888'}, lastCheckup:'2024-09-05' } },
  { id:'w18', employeeId:'AR-004', firstName:'Djamel', lastName:'Khelifi', unit:'Entretien', department:'Maintenance', position:'Mécanicien industriel', phone:'0558889999', status:'active', bloodType:'O-', lastSeen: new Date(Date.now()-11*60000).toISOString(), joinDate:'2019-11-28', companyId:'arcelormittal', medicalProfile:{ bloodType:'O-', allergies:['Latex'], chronicDiseases:[], medications:[], emergencyNotes:'Allergie au latex. Gants nitrile uniquement.', iceContact:{name:'Nawel Khelifi', relation:'Épouse', phone:'0668889999'}, lastCheckup:'2025-01-22' } },
  { id:'w19', employeeId:'SN-011', firstName:'Omar', lastName:'Mebarki', unit:'Unité C - Forage', department:'Extraction', position:'Géologue', phone:'0559990000', status:'active', bloodType:'A+', lastSeen: new Date(Date.now()-25*60000).toISOString(), joinDate:'2016-02-10', companyId:'sonatrach', medicalProfile:{ bloodType:'A+', allergies:[], chronicDiseases:[], medications:[], emergencyNotes:'', iceContact:{name:'Hadjira Mebarki', relation:'Épouse', phone:'0669990000'}, lastCheckup:'2024-06-15' } },
  { id:'w20', employeeId:'CV-005', firstName:'Ryad', lastName:'Laoufi', unit:'Administration', department:'RH', position:'Responsable RH', phone:'0550001111', status:'offline', bloodType:'B-', lastSeen: new Date(Date.now()-240*60000).toISOString(), joinDate:'2023-03-22', companyId:'cevital', medicalProfile:{ bloodType:'B-', allergies:[], chronicDiseases:['Migraine chronique'], medications:['Sumatriptan'], emergencyNotes:'Migraines fréquentes. Éviter lumière forte.', iceContact:{name:'Assia Laoufi', relation:'Épouse', phone:'0660001111'}, lastCheckup:'2024-08-30' } },
];

export const MOCK_ACTIVE_EMERGENCY: Emergency = {
  id: 'e-live-1',
  workerId: 'w1',
  workerName: 'Ahmed Mansouri',
  workerBadge: 'SN-001',
  unit: 'Unité A - Raffinage',
  type: 'cardiac',
  severity: 'critical',
  status: 'active',
  location: 'Zone de raffinage - Secteur 3',
  gpsCoordinates: { lat: 36.7525, lng: 3.0420 },
  startedAt: new Date().toISOString(),
  companyId: 'sonatrach',
  notes: 'Douleur thoracique intense, perte de conscience partielle',
  medicalProfile: WORKERS[0].medicalProfile,
};

export const EMERGENCY_HISTORY: Emergency[] = [
  { id:'e1', workerId:'w7', workerName:'Amar Zidane', workerBadge:'SN-007', unit:'Unité C - Forage', type:'cardiac', severity:'critical', status:'resolved', location:'Salle de commande Forage', startedAt: new Date(Date.now()-2*24*3600000).toISOString(), resolvedAt: new Date(Date.now()-2*24*3600000+25*60000).toISOString(), duration:25, respondedBy:'SAMU 15', companyId:'sonatrach' },
  { id:'e2', workerId:'w5', workerName:'Mourad Belkacemi', workerBadge:'SN-005', unit:'Unité D - Maintenance', type:'neurological', severity:'critical', status:'resolved', location:'Atelier mécanique', startedAt: new Date(Date.now()-3*24*3600000).toISOString(), resolvedAt: new Date(Date.now()-3*24*3600000+18*60000).toISOString(), duration:18, respondedBy:'Infirmerie site', companyId:'sonatrach' },
  { id:'e3', workerId:'w12', workerName:'Bilal Meziane', workerBadge:'AR-001', unit:'Haut-fourneau 1', type:'respiratory', severity:'moderate', status:'resolved', location:'Haut-fourneau 1 - Niveau 3', startedAt: new Date(Date.now()-5*24*3600000).toISOString(), resolvedAt: new Date(Date.now()-5*24*3600000+12*60000).toISOString(), duration:12, respondedBy:'Infirmerie site', companyId:'arcelormittal' },
  { id:'e4', workerId:'w4', workerName:'Khaled Aoudia', workerBadge:'SN-004', unit:'Unité A - Raffinage', type:'respiratory', severity:'moderate', status:'resolved', location:'Zone de stockage chimique', startedAt: new Date(Date.now()-6*24*3600000).toISOString(), resolvedAt: new Date(Date.now()-6*24*3600000+8*60000).toISOString(), duration:8, respondedBy:'Infirmerie site', companyId:'sonatrach' },
  { id:'e5', workerId:'w9', workerName:'Lamine Cherif', workerBadge:'CV-001', unit:'Ligne Production 1', type:'poisoning', severity:'critical', status:'resolved', location:'Cantine entreprise', startedAt: new Date(Date.now()-8*24*3600000).toISOString(), resolvedAt: new Date(Date.now()-8*24*3600000+35*60000).toISOString(), duration:35, respondedBy:'SAMU 15', companyId:'cevital' },
  { id:'e6', workerId:'w13', workerName:'Walid Boumaza', workerBadge:'AR-002', unit:'Laminoir', type:'trauma', severity:'moderate', status:'resolved', location:'Laminoir - Poste 4', startedAt: new Date(Date.now()-10*24*3600000).toISOString(), resolvedAt: new Date(Date.now()-10*24*3600000+15*60000).toISOString(), duration:15, respondedBy:'Infirmerie site', companyId:'arcelormittal' },
  { id:'e7', workerId:'w2', workerName:'Youcef Benmoussa', workerBadge:'SN-002', unit:'Unité B - Stockage', type:'cardiac', severity:'moderate', status:'false_alarm', location:'Bureau supervision', startedAt: new Date(Date.now()-12*24*3600000).toISOString(), resolvedAt: new Date(Date.now()-12*24*3600000+5*60000).toISOString(), duration:5, respondedBy:'Infirmerie site', companyId:'sonatrach' },
  { id:'e8', workerId:'w15', workerName:'Fares Bendjama', workerBadge:'SN-009', unit:'Unité A - Raffinage', type:'poisoning', severity:'moderate', status:'resolved', location:'Laboratoire chimie', startedAt: new Date(Date.now()-15*24*3600000).toISOString(), resolvedAt: new Date(Date.now()-15*24*3600000+22*60000).toISOString(), duration:22, respondedBy:'SAMU 15', companyId:'sonatrach' },
  { id:'e9', workerId:'w18', workerName:'Djamel Khelifi', workerBadge:'AR-004', unit:'Entretien', type:'trauma', severity:'minor', status:'resolved', location:'Atelier entretien', startedAt: new Date(Date.now()-18*24*3600000).toISOString(), resolvedAt: new Date(Date.now()-18*24*3600000+10*60000).toISOString(), duration:10, respondedBy:'Infirmerie site', companyId:'arcelormittal' },
  { id:'e10', workerId:'w11', workerName:'Hamza Kerboua', workerBadge:'CV-003', unit:'Entrepôt', type:'trauma', severity:'minor', status:'resolved', location:'Entrepôt - Allée 5', startedAt: new Date(Date.now()-20*24*3600000).toISOString(), resolvedAt: new Date(Date.now()-20*24*3600000+7*60000).toISOString(), duration:7, respondedBy:'Infirmerie site', companyId:'cevital' },
  { id:'e11', workerId:'w8', workerName:'Kamel Bouzid', workerBadge:'SN-008', unit:'Unité D - Maintenance', type:'fire', severity:'critical', status:'resolved', location:'Tableau électrique P3', startedAt: new Date(Date.now()-22*24*3600000).toISOString(), resolvedAt: new Date(Date.now()-22*24*3600000+30*60000).toISOString(), duration:30, respondedBy:'Pompiers + SAMU', companyId:'sonatrach' },
  { id:'e12', workerId:'w6', workerName:'Sofiane Hadjadj', workerBadge:'SN-006', unit:'Unité B - Stockage', type:'cardiac', severity:'critical', status:'resolved', location:'Salle de repos', startedAt: new Date(Date.now()-25*24*3600000).toISOString(), resolvedAt: new Date(Date.now()-25*24*3600000+40*60000).toISOString(), duration:40, respondedBy:'SAMU 15', companyId:'sonatrach' },
  { id:'e13', workerId:'w17', workerName:'Samir Bensaid', workerBadge:'CV-004', unit:'Ligne Production 3', type:'respiratory', severity:'minor', status:'false_alarm', location:'Zone conditionnement', startedAt: new Date(Date.now()-28*24*3600000).toISOString(), resolvedAt: new Date(Date.now()-28*24*3600000+4*60000).toISOString(), duration:4, respondedBy:'Infirmerie site', companyId:'cevital' },
  { id:'e14', workerId:'w19', workerName:'Omar Mebarki', workerBadge:'SN-011', unit:'Unité C - Forage', type:'trauma', severity:'moderate', status:'resolved', location:'Site forage - Puits 7', startedAt: new Date(Date.now()-30*24*3600000).toISOString(), resolvedAt: new Date(Date.now()-30*24*3600000+20*60000).toISOString(), duration:20, respondedBy:'Infirmerie site', companyId:'sonatrach' },
  { id:'e15', workerId:'w3', workerName:'Rachid Ferhat', workerBadge:'SN-003', unit:'Unité C - Forage', type:'fire', severity:'moderate', status:'resolved', location:'Zone de forage - Secteur 1', startedAt: new Date(Date.now()-33*24*3600000).toISOString(), resolvedAt: new Date(Date.now()-33*24*3600000+28*60000).toISOString(), duration:28, respondedBy:'Pompiers site', companyId:'sonatrach' },
];

export const SAFETY_OFFICERS: SafetyOfficer[] = [
  { id:'so1', name:'Kamel Benali', role:'Responsable HSE', phone:'0770000001', email:'k.benali@sonatrach.dz', companyId:'sonatrach', receivesAlerts:true },
  { id:'so2', name:'Samira Mokrani', role:'Infirmière chef', phone:'0770000002', email:'s.mokrani@sonatrach.dz', companyId:'sonatrach', receivesAlerts:true },
  { id:'so3', name:'Hocine Larbi', role:'Chef sécurité', phone:'0770000003', email:'h.larbi@sonatrach.dz', companyId:'sonatrach', receivesAlerts:false },
];

export const MONTHLY_DATA: MonthlyData[] = [
  { month:'Nov', incidents:3, resolved:3 },
  { month:'Déc', incidents:5, resolved:4 },
  { month:'Jan', incidents:2, resolved:2 },
  { month:'Fév', incidents:7, resolved:6 },
  { month:'Mar', incidents:4, resolved:4 },
  { month:'Avr', incidents:6, resolved:5 },
  { month:'Mai', incidents:3, resolved:2 },
];

export const EMERGENCY_TYPE_DISTRIBUTION: ChartDataPoint[] = [
  { name:'Cardiaque', value:5, color:'#E53935' },
  { name:'Traumatisme', value:4, color:'#FF9800' },
  { name:'Incendie', value:2, color:'#FF5722' },
  { name:'Respiratoire', value:3, color:'#2196F3' },
  { name:'Neurologique', value:1, color:'#9C27B0' },
  { name:'Intoxication', value:2, color:'#4CAF50' },
];
